const elements = {
    home: [{data: {name: 'Home'}}],
    williamsSummit: [{data: {id: 'Williams Summit', name: 'Williams Summit'}}],
    smallFamilyData: [
        {data: { id: 'Davey', name: 'Davey'} },
        {data: { id: 'Maddie', name: 'Maddie'} },
        {data: { id: 'Lisa', name: 'Lisa'} },
        {data: { id: 'Aaron', name: 'Aaron'} },
        {data: { name: 'married to', source: 'Lisa',target: 'Aaron'}},
        {data: { name: 'parent of', source: 'Lisa',target: 'Davey'}},
        {data: { name: 'parent of', source: 'Lisa',target: 'Maddie'}},
        {data: { name: 'parent of', source: 'Aaron',target: 'Davey'}},
        {data: { name: 'parent of', source: 'Aaron',target: 'Maddie'}},
        {data: { name: 'sibling of', source: 'Davey', target: 'Maddie'}}
    ],
    bigFamilyData: [
        { data: { name: 'Davey'} },
        { data: { name: 'Maddie' } },
        { data: { name: 'Lisa' } },
        { data: { name: 'Aaron' } },
        //mom's snamee
        { data: { name: 'Marcella' } },
        { data: { name: 'Steve' } },
        { data: { name: 'David Rosen' } },
        { data: { name: 'David Sax' } },
        //related to Julie
        { data: { name: 'Julie' } },
        { data: { name: 'Michael' } },
        { data: { name: 'Beep' } },
        { data: { name: 'Suzan' } },
        { data: { name: 'Ann' } },
        { data: { name: 'Jeremy' } },
        { data: { name: 'Josh' } },
        { data: { name: 'Dan' } },
        { data: { name: 'Jamie' } },
        //related to Irma
        { data: { name: 'Irma' } },
        { data: { name: 'Henrietta Lang' } },
        { data: { name: 'Issacher Burt Rothschild' } },
        { data: { name: 'Burt' } },
        { data: { name: 'Eddie' } },
        { data: { name: 'Krista' } },
        //Krista's side
        { data: { name: 'Edwin Flint Moore', nickname: 'Ted'} }, //dad
        { data: { name: 'Carolyn Moore' } }, //mom
        { data: { name: 'Kellye Nicol', nickname: "Suing Sister" } },
        { data: { name: 'Rustyn Mooney', nickname: "Good Sister" } },
        { data: { name: 'Heidi Moore' } },
        { data: { name: 'Timothy Everett Moore' } },
        { data: { name: 'Heidi Floros', nickname: "bio greek sister" } }, //biological sister, greek
        { data: { name: 'Romy' } },
        //dad's side
        { data: { name: 'Barbara' } },
        { data: { name: 'Jerome' } },
        { data: { name: 'Howard' } },
        { data: { name: 'Jon',  /*remarried_kid: "true"*/} },
        { data: { name: 'Brian' } },
        { data: { name: 'Margie' } },
        { data: { name: 'Sarah' } },
        { data: { name: 'Bill' } },
        { data: { name: 'Shirley' } },
        { data: { name: 'Abraham' } },
        { data: { name: 'Alvin' } },
        //pasha's family
        { data: { name: 'Pasha' } },
        { data: { name: 'Sanam' } },
        { data: { name: 'Shad' } },
        { data: { name: 'Leila' } },
        //Davey's other town friends
        { data: { name: 'Connor' } },
        { data: { name: 'William' } },
        { data: { name: 'Matteo' } },
        //Matteo's family
        {data: {name: 'Luca'}},
        //relations
        {data: { name: 'parent of', source: 'Lisa',target: "Davey"}},
        {data: { name: 'parent of', source: 'Lisa',target: 'Maddie'}},
        {data: { name: 'parent of', source: 'Barbara',target: 'Aaron'}},
        {data: { name: 'parent of', source: 'Barbara',target: 'Jon'}},
        {data: { name: 'parent of', source: 'Marcella',target: 'Lisa'}},
        {data: { name: 'parent of', source: 'Marcella',target: 'Burt'}},
        {data: { name: 'parent of', source: 'Krista',target: 'Eddie'}},
        {data: { name: 'parent of', source: 'Krista',target: 'Romy'}},
        {data: { name: 'parent of', source: 'Edwin Flint Moore',target: 'Krista'}},
        {data: { name: 'parent of', source: 'Edwin Flint Moore',target: 'Kellye Nicol'}},
        {data: { name: 'parent of', source: 'Edwin Flint Moore',target: 'Rustyn Mooney'}},
        {data: { name: 'parent of', source: 'Edwin Flint Moore',target: 'Timothy Everett Moore'}},
        {data: { name: 'married to', source: 'Edwin Flint Moore',target: 'Carolyn Moore'}},
        {data: { name: 'married to', source: 'Lisa',target: 'Aaron'}},
        {data: { name: 'married to', source: 'Krista',target: 'Burt'}},
        {data: { name: 'married to', source: 'Marcella',target: 'David Rosen'}},
        {data: { name: 'remarried to', source: 'Marcella',target: 'David Sax'}},
        {data: { name: 'partner', source: 'Jon',target: 'Brian'}},
        {data: { name: 'partner', source: 'Marcella',target: 'Steve'}},
        {data: { name: 'parent of', source: 'Irma',target: 'Marcella'}},
        {data: { name: 'parent of', source: 'Irma',target: 'Julie'}},
        {data: { name: 'married to', source: 'Julie',target: 'Michael'}},
        {data: { name: 'parent of', source: 'Julie',target: 'Beep'}},
        {data: { name: 'parent of', source: 'Julie',target: 'Suzan'}},
        {data: { name: 'parent of', source: 'Julie',target: 'Ann'}},
        {data: { name: 'parent of', source: 'Beep',target: 'Jeremy'}},
        {data: { name: 'parent of', source: 'Beep',target: 'Josh'}},
        {data: { name: 'parent of', source: 'Beep',target: 'Jamie'}},
        {data: { name: 'married to', source: 'Beep',target: 'Dan'}},
        {data: { name: 'parent of', source: 'Shirley',target: 'Barbara'}},
        {data: { name: 'parent of', source: 'Shirley',target: 'Margie'}},
        {data: { name: 'married to', source: 'Shirley',target: 'Abraham'}},
        {data: { name: 'sibling', source: 'Shirley',target: 'Alvin'}},
        {data: { name: 'married to', source: 'Margie',target: 'Bill'}},
        {data: { name: 'parent', source: 'Margie',target: 'Sarah'}},
        {data: { name: 'originally married to', source: 'Barbara',target: 'Jerome'}},
        {data: { name: 'divorced from', source: 'Barbara',target: 'Jerome'}},
        {data: { name: 'married to', source: 'Barbara',target: 'Howard'}},
        {data: { name: 'married to', source: 'Sanam',target: 'Shad'}},
        {data: { name: 'parent of', source: 'Sanam',target: 'Pasha'}},
        {data: { name: 'parent of', source: 'Sanam',target: 'Leila'}},
        {data: { name: 'boys with', source: 'Davey',target: 'Pasha'}},
        {data: { name: 'boys with', source: 'Davey',target: 'Connor'}},
        {data: { name: 'boys with', source: 'Davey',target: 'William'}},
        {data: { name: 'boys with', source: 'Davey',target: 'Matteo'}},
        {data: { name: 'sibling of', source: 'Luca',target: 'Matteo'}}
    ],
    harryPotter: [
        {data: { id: 'James Potter'} }, {data: { id: 'Lily Potter'} },
        {data: { id: 'Severus Snape'} }, {data: { id: 'Sirius Black'} },
        {data: { type: 'married', source: 'James Potter',target: 'Lily Potter'}},
        {data: { type: 'hates', source: 'Severus Snape',target: 'James Potter'}},
        {data: { type: 'best friends', source: 'James Potter',target: 'Sirius Black'}},
        {data: { type: 'dislikes', source: 'Sirius Black', target: "Severus Snape"}},
        {data: { type: 'loves', source: 'Severus Snape', target: "Lily Potter"}},
        {data: { type: 'likes', source: 'Lily Potter', target: "Severus Snape"}}
    ],
    rocketScience: [
        {data: { id: 'combustion'} }, {data: { id: 'fuel'} },
        {data: { id: 'oxygen'} }, {data: { id: 'ignition threshold'} },
        {data: { id: 'heat'} }, {data: { id: 'chemical reaction'} },
        {data: { id: 'fire'} }, {data: { id: 'rocket'} },
        {data: { id: 'propellant system'} },
        {data: { type: 'uses', source: 'combustion',target: 'oxygen'}},
        {data: { type: 'uses', source: 'combustion',target: 'fuel'}},
        {data: { type: 'seen as', source: 'combustion',target: 'fire'}},
        {data: { type: 'launches', source: 'combustion', target: "rocket"}},
        {data: { type: 'causes', source: 'heat', target: "combustion"}},
        {data: { type: 'has', source: 'fuel', target: "ignition threshold"}},
        {data: { type: 'is a quantity of', source: 'ignition threshold', target: "heat"}},
        {data: { type: 'is a type of', source: 'combustion', target: "chemical reaction"}},
        {data: { type: 'occurs in', source: 'combustion', target: "propellant system"}},
        {data: { type: 'at bottom of', source: 'propellant system', target: "rocket"}}
    ]
};
export default elements;
